---
galaxy_info:
  role_name: aap_vm
  namespace: ocp4_disconnected_helper
  author: Platform Team
  description: AAP VM deployment and configuration
  company: ocp4-disconnected-helper
  license: MIT
  min_ansible_version: "2.15"

  platforms:
    - name: EL
      versions:
        - "9"

  galaxy_tags:
    - aap
    - ansible-automation-platform
    - openshift
    - disconnected

dependencies:
  - role: common_vm
