---
- name: Pull the latest catalog listing for {{ operator.catalog }}
  block:
    - ansible.builtin.command: "{{ oc_path.stdout }} mirror list operators --catalog={{ operator.catalog }}"
      register: catalog_listing
      environment:
        PATH: "{{ ansible_env.PATH }}:/usr/local/bin"
      changed_when: false
  rescue:
    - name: Handle error in catalog listing
      ansible.builtin.debug:
        msg: "Failed to pull catalog listing for {{ operator.catalog }}. Error: {{ catalog_listing.stderr }}"
  always:
    - name: Display catalog listing for debugging
      ansible.builtin.debug:
        var: catalog_listing
      when: debug_mode

- name: Initialize catalog_operators as a list
  ansible.builtin.set_fact:
    catalog_operators: []


- name: Verify package existence in the catalog with channel and version
  ansible.builtin.assert:
    that: |
      catalog_operators.get(item.name) is defined and
      catalog_operators[item.name]['channel'] == item.channel
    fail_msg: |
      Package {{ item.name }} does not exist in {{ operator.catalog }}
      or is not available in the specified channel {{ item.channel }}.
      Please check the package name and channel, and try again.
  loop: "{{ operator.packages | default([]) }}"
  loop_control:
    label: "{{ item.name }}"
  when: registry_check is defined and not registry_check.changed




- name: Set fact for determined_operator_catalog
  ansible.builtin.set_fact:
    determined_operator_catalog: "{{ catalog_operators }}"


