---
- name: Cleanup
  hosts: registry_hosts
  become: true
  gather_facts: false

  tasks:
    - name: Debug /tmp directory permissions
      debug:
        msg: "Permissions of /tmp: {{ lookup('stat', '/tmp').mode }}"

    - name: Stop Quay container service
      become: true
      systemd:
        name: quay-container
        state: stopped
        enabled: false
      failed_when: false

    - name: Remove test images from local storage
      become: true
      command: "{{ item }}"
      with_items:
        - podman rmi localhost:8080/test/hello-world:latest --force
        - podman rmi docker.io/hello-world:latest --force
      failed_when: false
      changed_when: false

    - name: Clean up registry data directory  
      become: true
      file:
        path: "{{ item }}"
        state: absent
      loop:
        - /var/lib/quay
        - /etc/quay
        - /etc/systemd/system/quay-container.service
      failed_when: false

    - name: Clean container storage
      command: podman system prune -af
      failed_when: false
      changed_when: false

    - name: Reload systemd
      systemd:
        daemon_reload: yes
      failed_when: false
