---
- name: Converge
  hosts: registry_hosts
  become: true
  gather_facts: true

  vars_files:
    - ../../extra_vars/setup-quay-registry-vars.yml

  pre_tasks:
    - name: Include setup-quay-registry playbook
      include_tasks: ../../playbooks/setup-quay-registry.yml

  tasks:
    - name: Wait for Quay to be ready
      uri:
        url: "http://localhost:8080/health/instance"
        method: GET
        status_code: 200
      register: result
      until: result.status == 200
      retries: 60
      delay: 5

    - name: Verify Quay is running
      command: podman ps
      register: containers
      failed_when: "'quay' not in containers.stdout"

    - name: Create test repository
      uri:
        url: "http://localhost:8080/api/v1/repository"
        method: POST
        body_format: json
        body:
          repository: "test/hello-world"
          visibility: "public"
          description: "Test repository"
        status_code: 201
      register: create_repo
      changed_when: create_repo.status == 201

    - name: Pull test image
      command: podman pull docker.io/hello-world:latest
      register: pull_result
      changed_when: pull_result.rc == 0

    - name: Tag test image for Quay
      command: podman tag docker.io/hello-world:latest localhost:8080/test/hello-world:latest
      register: tag_result
      changed_when: tag_result.rc == 0

    - name: Push test image to Quay
      command: podman push localhost:8080/test/hello-world:latest --tls-verify=false
      register: push_result
      changed_when: push_result.rc == 0
