---
dependency:
  name: galaxy
  options:
    role-file: collections/requirements.yml

driver:
  name: vagrant
  provider:
    name: libvirt

platforms:
  - name: registry-test
    box: generic/rhel8
    memory: 8192
    cpus: 4
    provider_options:
      storage_pool_name: kvm_pool
    provider_raw_config_args:
      - "storage :file, :size => '100G'"
    interfaces:
      - network_name: kvm_net
        type: bridge
    groups:
      - registry_hosts

  - name: mirror-test
    box: generic/rhel8
    memory: 4096
    cpus: 2
    provider_options:
      storage_pool_name: kvm_pool
    interfaces:
      - network_name: kvm_net
        type: bridge
    groups:
      - mirror_hosts

provisioner:
  name: ansible
  env:
    ANSIBLE_ROLES_PATH: ../../roles
  inventory:
    group_vars:
      registry_hosts:
        ansible_user: vagrant
        ansible_become: true
      mirror_hosts:
        ansible_user: vagrant
        ansible_become: true
  playbooks:
    prepare: prepare.yml
    converge: converge.yml
    verify: verify.yml
    cleanup: cleanup.yml
    destroy: destroy.yml
  options:
    vvv: true
    diff: true
  lint:
    name: ansible-lint

verifier:
  name: testinfra
  lint:
    name: flake8
  options:
    connection: ansible
    ansible-inventory: .molecule/ansible_inventory

lint: |
  set -e
  yamllint .
  ansible-lint
  flake8

scenario:
  name: default
  test_sequence:
    - dependency
    - lint
    - cleanup
    - destroy
    - syntax
    - create
    - prepare
    - converge
    - idempotence
    - verify
    - cleanup
    - destroy
