---
dependency:
  name: galaxy
  options:
    role-file: collections/requirements.yml
    ignore-certs: true
    ignore-errors: true

driver:
  name: podman

platforms:
  - name: quay-vm
    pre_build_image: true
    memory: 8192
    cpus: 4
    ansible_port: 8080
    groups:
      - quay_vms
  - name: harbor-vm
    pre_build_image: true
    memory: 8192
    cpus: 4
    ansible_port: 8081
    groups:
      - harbor_vms
  - name: jfrog-vm
    pre_build_image: true
    memory: 8192
    cpus: 4
    ansible_port: 8082
    groups:
      - jfrog_vms

provisioner:
  name: ansible
  inventory:
    group_vars:
      quay_vms:
        ansible_user: centos
        ansible_ssh_private_key_file: /home/lab-user/.ssh/id_rsa
      harbor_vms:
        ansible_user: ubuntu
        ansible_ssh_private_key_file: /home/lab-user/.ssh/id_rsa
      jfrog_vms:
        ansible_user: centos
        ansible_ssh_private_key_file: /home/lab-user/.ssh/id_rsa
  env:
    ANSIBLE_ROLES_PATH: ../../roles
    ANSIBLE_REMOTE_TMP: /tmp
  config_options:
    defaults:
      remote_tmp: /tmp
  playbooks:
    create: create.yml
    destroy: destroy.yml
    prepare: prepare.yml
    converge: converge.yml
    verify: verify.yml
    cleanup: cleanup.yml
  options:
    vvv: true
    diff: true

verifier:
  name: testinfra
  options:
    connection: ansible
    ansible-inventory: ../../inventory

scenario:
  name: default
  test_sequence:
    - dependency
    - cleanup
    - destroy
    - syntax
    - create
    - prepare
    - converge
    - idempotence
    - verify
    - cleanup
    - destroy
