---
- name: Prepare
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Wait for Quay containers to be ready
      containers.podman.podman_container_info:
        name: "{{ item.name }}"
      register: container_info
      until: container_info.containers | length > 0 and container_info.containers[0].State.Running
      retries: 10
      delay: 3
      loop: "{{ molecule_yml.platforms }}"

    - name: Debug container info
      debug:
        var: container_info
        verbosity: 1
