---
- name: Verify
  hosts: quay_vms
  gather_facts: true
  tasks:
    - name: Check Quay service status
      service_facts:
      register: services_state

    - name: Get list of running containers
      command: podman ps --format "{{.Names}}"
      register: container_list
      changed_when: false

    - name: Verify Quay container is running
      assert:
        that:
          - "'quay-mirror' in container_list.stdout"
        fail_msg: "Quay container is not running"

    - name: Check Quay ports availability
      wait_for:
        host: "{{ inventory_hostname }}"
        port: "{{ item }}"
        timeout: 30
      loop:
        - 8443
        - 80
      register: port_check
      failed_when: not port_check.state == "started"

    - name: Check Quay health endpoint
      uri:
        url: "https://{{ inventory_hostname }}:8443/health/instance"
        method: GET
        return_content: yes
        validate_certs: no
      register: health_check
      failed_when: health_check.status != 200
