---
- name: Verify
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Check Quay container status
      containers.podman.podman_container_info:
        name: "{{ item.name }}"
      register: container_info
      loop: "{{ molecule_yml.platforms }}"
      failed_when: not container_info.containers[0].State.Running

    - name: Check Quay port availability
      wait_for:
        host: localhost
        port: "{{ item.ansible_port }}"
        timeout: 10
      register: port_check
      loop: "{{ molecule_yml.platforms }}"
      failed_when: not port_check.state == "started"

    - name: Check Quay health endpoint
      uri:
        url: "http://localhost:{{ item.ansible_port }}/health/instance"
        method: GET
        return_content: yes
      register: health_check
      loop: "{{ molecule_yml.platforms }}"
      failed_when: health_check.status != 200

    - name: Debug test container status
      debug:
        var: container_info
        verbosity: 1
