---
# Prerequisites:
## Modify the inventory file to reflect your environment
## The user must have password-less sudo access
## The user must have password-less ssh access to the remote hosts
## You need a Pull Secret from the RH Registry: https://cloud.redhat.com/openshift/install/pull-secret

- name: Downloads OpenShift and Operator Catalog container images and stores them as TAR files to be transported into a disconnected enclave
  hosts: localhost
  gather_facts: true
  become: true
  tasks:
    - name: Make sure basic packages are installed
      ansible.builtin.package:
        name: "{{ base_packages }}"
        state: present

    - name: Setup Cockpit because I am a lazy admin
      when: setup_cockpit
      block:
        - name: Install Cockpit because it's nice to have
          ansible.builtin.package:
            name: ['cockpit', 'cockpit-storaged']
            state: present

        - name: Enable Cockpit
          ansible.builtin.service:
            name: cockpit.socket
            state: started
            enabled: true

    - name: Check for the oc binary
      block:
        - name: Check if oc is installed
          ansible.builtin.command: which oc
          changed_when: false
          failed_when: oc_installed.rc not in [0, 1]
          register: oc_installed

        - name: Install the oc binary
          when: oc_installed.rc not in [0]
          block:
            - name: Download the OC binary if it is not present
              ansible.builtin.get_url:
                url: https://mirror.openshift.com/pub/openshift-v4/{{ ansible_architecture }}/clients/ocp/stable/openshift-client-linux.tar.gz
                dest: /tmp/openshift-client-linux.tar.gz
                mode: 0755

            - name: Extract the oc binary
              ansible.builtin.unarchive:
                src: /tmp/openshift-client-linux.tar.gz
                dest: /usr/local/bin
                remote_src: true
                creates: /usr/local/bin/oc
                mode: 0755

            - name: Enable binary completion for oc
              ansible.builtin.shell: /usr/local/bin/oc completion bash > /etc/bash_completion.d/oc_completion.sh
              args:
                creates: /etc/bash_completion.d/oc_completion.sh

    - name: Check for the oc mirror plugin
      block:
        - name: Check if oc is installed
          ansible.builtin.command: which oc-mirror
          changed_when: false
          failed_when: oc_mirror_installed.rc not in [0, 1]
          register: oc_mirror_installed

        - name: Install the oc-mirror plugin
          when: oc_mirror_installed.rc not in [0]
          block:
            - name: Download the oc-mirror plugin
              ansible.builtin.get_url:
                url: https://mirror.openshift.com/pub/openshift-v4/x86_64/clients/ocp/stable/oc-mirror.tar.gz
                dest: /tmp/oc-mirror.tar.gz
                mode: 0755

            - name: Extract the oc-mirror binary
              ansible.builtin.unarchive:
                src: /tmp/oc-mirror.tar.gz
                dest: /usr/local/bin
                remote_src: true
                creates: /usr/local/bin/oc-mirror
                mode: 0755

            - name: Enable binary completion for oc-mirror
              ansible.builtin.shell: /usr/local/bin/oc-mirror completion bash > /etc/bash_completion.d/oc-mirror_completion.sh
              args:
                creates: /etc/bash_completion.d/oc-mirror_completion.sh

    - name: Make sure that the root user has /usr/local/bin in its PATH
      block:
        - name: Check if /usr/local/bin is already defined
          ansible.builtin.lineinfile:
            state: absent
            path: "/root/.bashrc"
            regexp: "/usr/local/bin"
          check_mode: true
          changed_when: false # This just makes things look prettier in the logs
          register: path_check

        - name: Define /usr/local/bin if undefined
          ansible.builtin.lineinfile:
            state: present
            path: "/root/.bashrc"
            line: "export PATH=$PATH:/usr/local/bin"
          when: path_check.found == 0

    - name: Get the path to oc, discount double check
      ansible.builtin.command:
        cmd: which oc
      environment:
        PATH: "{{ ansible_env.PATH }}:/usr/local/bin"
      register: oc_path
      changed_when: false

    - name: Create the $HOME/.docker directory
      ansible.builtin.file:
        path: /root/.docker
        state: directory
        owner: root
        group: root
        mode: 0700

    - name: Test network speed
      ansible.builtin.command: "ping -c 4 google.com"
      register: network_test
      changed_when: false

    - name: Fail if network latency is too high
      ansible.builtin.fail:
        msg: "Network latency is too high. Please ensure better connectivity."
      when: network_test.stdout is search('time=([1-9][0-9]{2,})')  # Fail if latency is above a certain threshold (e.g., 100ms)

    - name: if target_mirror_path does not exist create the directory 
      ansible.builtin.file:
        path: "{{ target_mirror_path }}"
        state: directory
        owner: root
        group: root
        mode: 0755

    - name: Copy the Red Hat Registry Pull Secret to the remote host
      when: local_rh_pull_secret_path is defined
      ansible.builtin.copy:
        src: "{{ local_rh_pull_secret_path }}"
        dest: "{{ target_rh_pull_secret_path }}"
        mode: 0600
        backup: true

    - name: Store the Red Hat Registry Pull Secret on the remote host when defined as a variable
      when: local_rh_pull_secret_path is not defined and rh_pull_secret is defined
      ansible.builtin.copy:
        content: "{{ rh_pull_secret }}"
        dest: "{{ target_rh_pull_secret_path }}"
        mode: 0600
        backup: true

    - name: Clear the mirror path if requested
      when: clean_mirror_path
      block:
        - name: Find any tar files that
