name: 'Ansible Lint and Refactor with Ollama API'

on:
  push:
    branches:
      - lint-testing
  pull_request:
    branches:
      - lint-testing

jobs:
  start-ollama:
    runs-on: ubuntu-latest
    outputs:
      api_url: ${{ steps.ollama-start.outputs.api_url }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Start Ollama API in Docker with Secrets
        id: ollama-start
        env:
          MODEL: ${{ secrets.MODEL }}
          EDITOR_MODEL: ${{ secrets.EDITOR_MODEL }}
        run: |
          # Pull and run the Ollama Docker container with environment variables for model settings
          docker run -d --name ollama-api -p 11434:11434 \
            -e MODEL="${MODEL}" \
            -e EDITOR_MODEL="${EDITOR_MODEL}" \
            ollama/ollama:latest

          # Wait until Ollama API is up
          until curl -s http://localhost:11434/health; do
            echo "Waiting for Ollama API to be ready..."
            sleep 5
          done

          # Set the API URL as output
          echo "::set-output name=api_url::http://localhost:11434"

  ansible-lint-and-refactor:
    needs: start-ollama
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Adjust Workspace Permissions
        run: |
          sudo chown -R 1000:1000 ${{ github.workspace }}

      - name: Run Ansible Lint and Refactor in Container
        uses: addnab/docker-run-action@v3
        with:
          image: quay.io/takinosh/ansible-lint-and-refactor:da3de0378544e860d38371435a8b42af8981fb70
          options: |
            -v ${{ github.workspace }}:/workspace
            -e OLLAMA_API_BASE=${{ needs.start-ollama.outputs.api_url }}
            -e MODEL=${{ secrets.MODEL }}
            -e EDITOR_MODEL=${{ secrets.EDITOR_MODEL }}
            -e PLAYBOOKS_DIR=playbooks/
            -e TASKS_DIR=playbooks/tasks/
          run: |
            set -e
            whoami
            ls -lath /workspace
            ls -ld /workspace/.git
            cd /workspace
            echo "Connecting to Ollama API at ${OLLAMA_API_BASE}"
            echo "USING MODEL: ${MODEL}"
            /opt/ansible-venv/bin/ansible-lint-script.sh || exit 1

      - name: Stop Ollama API
        if: always()
        run: docker stop ollama-api && docker rm ollama-api
